ft_model:
  id: angnami/distilbert-base-uncased-finetuned-sst-2-english:1.0.0 
model:
  id: distilbert/distilbert-base-uncased-finetuned-sst-2-english
setup:
  device: cuda:0
dataset:
  file: "inference.csv"
